### ISSUE TITLE
The name of the project works is appealing, but what is the purpose of this project?

### ISSUE THREAD

**Issue by owiofwm2i** [devgunho/Network_Tracking_Project#1]

**Comment by gunh0** [comment]
It is a project that is still lacking a lot, and there are many things to improve.
First of all, the purpose of this project is to collect large quantities of encrypted packets from the Tor browser.

For this purpose, Command each client (agent, for collection) for collection through the 'pcap_collector/server_GUI-PyQt'.
'pcap_collector/client/client.py' / It serves to receive commands through this.

Finally, it analyzes and tracks packets collected through deep learning.
